[project]
name = "gpt2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.12"
dependencies = [
    "accelerate>=1.12.0",
    "datatrove[io,processing,multilingual]",
    "datasets>=4.5.0",
    "duckdb>=1.4.4",
    "huggingface-hub>=1.4.1",
    "hydra-core>=1.3.2",
    "ipykernel>=7.2.0",
    "lance>=1.2.1",
    "lancedb>=0.29.2",
    "pillow>=12.1.1",
    "pyarrow>=23.0.0",
    "tokenizer>=3.6.2",
    "tokenizers>=0.22.2",
    "torch>=2.10.0",
    "tqdm>=4.67.3",
    "transformers>=5.1.0",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cu130" }]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
